<?php

/*
|--------------------------------------------------------------------------
| VVS FLAWLESS - internal watch search vocabulary
|--------------------------------------------------------------------------
|
| These aliases are used ONLY for internal discovery/filtering.
| They must never replace the public VVS product name, Product.brand,
| Product.name, manufacturer, schema.org brand or public H1.
|
| Families are intentionally conservative. When a visual family is not
| sufficiently clear, the entry keeps descriptive aliases only.
|
*/

return [
    'models' => [
        'blue-round' => [
            'families' => [
                ['value' => 'rolex', 'label' => 'Rolex'],
            ],
            'aliases' => [
                'Rolex',
                'Rolex Datejust',
                'Datejust',
                'Date Just',
                'Rolex Jubilee',
                'Jubilee',
                'Rolex iced out',
                'Rolex bustdown',
                'Rolex moissanite',
            ],
            'keywords' => [
                'pink',
                'rose',
                'pave',
                'pavé',
                'iced out',
                'bustdown',
                'moissanite',
                'VVS',
                'round',
                'ronde',
            ],
        ],

        'twotone-round' => [
            'families' => [],
            'aliases' => [
                'montre squelette',
                'squelette',
                'skeleton watch',
                'skeleton',
                'iced out skeleton',
                'moissanite skeleton',
            ],
            'keywords' => [
                'bicolore',
                'two tone',
                'two-tone',
                'champagne',
                'gold',
                'or',
                'iced out',
                'moissanite',
                'VVS',
            ],
        ],

        'square-roman' => [
            'families' => [
                ['value' => 'cartier', 'label' => 'Cartier'],
            ],
            'aliases' => [
                'Cartier',
                'Cartier Santos',
                'Santos',
                'Santos Cartier',
                'Cartier iced out',
                'Santos iced out',
                'Cartier bustdown',
                'Cartier moissanite',
            ],
            'keywords' => [
                'square',
                'carree',
                'carrée',
                'roman',
                'romains',
                'iced out',
                'moissanite',
                'VVS',
            ],
        ],

        'black-square' => [
            'families' => [
                ['value' => 'cartier', 'label' => 'Cartier'],
            ],
            'aliases' => [
                'Cartier',
                'Cartier Santos',
                'Santos',
                'Santos Cartier',
                'Cartier black',
                'Cartier noir',
                'Santos black',
                'Cartier iced out',
                'Cartier moissanite',
            ],
            'keywords' => [
                'black',
                'noir',
                'square',
                'carree',
                'carrée',
                'roman',
                'romains',
                'iced out',
                'moissanite',
                'VVS',
            ],
        ],

        'black-stainless' => [
            'families' => [
                ['value' => 'audemars-piguet', 'label' => 'Audemars Piguet'],
            ],
            'aliases' => [
                'Audemars Piguet',
                'Audemars',
                'Audemard',
                'AP',
                'Royal Oak',
                'AP Royal Oak',
                'Audemars Royal Oak',
                'AP iced out',
                'AP bustdown',
                'AP moissanite',
            ],
            'keywords' => [
                'black',
                'noir',
                'stainless',
                'acier',
                'silver',
                'argent',
                'integrated bracelet',
                'bracelet integre',
                'iced out',
                'moissanite',
                'VVS',
            ],
        ],

        'red-roman' => [
            'families' => [
                ['value' => 'cartier', 'label' => 'Cartier'],
            ],
            'aliases' => [
                'Cartier',
                'Cartier Santos',
                'Santos',
                'Santos Cartier',
                'Cartier red',
                'Cartier rouge',
                'Cartier iced out',
                'Cartier moissanite',
            ],
            'keywords' => [
                'red',
                'rouge',
                'roman',
                'romains',
                'iced out',
                'moissanite',
                'VVS',
            ],
        ],

        'jubilee' => [
            'families' => [
                ['value' => 'rolex', 'label' => 'Rolex'],
            ],
            'aliases' => [
                'Rolex',
                'Rolex Datejust',
                'Datejust',
                'Date Just',
                'Rolex Jubilee',
                'Jubilee',
                'Rolex iced out',
                'Rolex bustdown',
                'Rolex moissanite',
            ],
            'keywords' => [
                'jubilee',
                'silver',
                'argent',
                'iced out',
                'bustdown',
                'moissanite',
                'VVS',
            ],
        ],

        'sport-black-strap' => [
            'families' => [
                ['value' => 'rolex', 'label' => 'Rolex'],
            ],
            'aliases' => [
                'Rolex',
                'Rolex Daytona',
                'Daytona',
                'Daytona iced out',
                'Rolex chronograph',
                'Oysterflex',
                'Rolex iced out',
                'Rolex moissanite',
            ],
            'keywords' => [
                'chronograph',
                'chronographe',
                'black strap',
                'bracelet noir',
                'rubber strap',
                'sport',
                'black',
                'noir',
                'iced out',
                'moissanite',
                'VVS',
            ],
        ],

        'gold-black-daydate' => [
            'families' => [
                ['value' => 'rolex', 'label' => 'Rolex'],
            ],
            'aliases' => [
                'Rolex',
                'Rolex Day-Date',
                'Rolex Day Date',
                'Day-Date',
                'Day Date',
                'Daydate',
                'Rolex President',
                'Rolex Presidential',
                'President',
                'Presidential',
                'Rolex iced out',
                'Rolex bustdown',
                'Rolex moissanite',
            ],
            'keywords' => [
                'gold',
                'or',
                'yellow gold',
                'or jaune',
                'black',
                'noir',
                'day',
                'date',
                'iced out',
                'moissanite',
                'VVS',
            ],
        ],

        'rose-skeleton' => [
            'families' => [
                ['value' => 'audemars-piguet', 'label' => 'Audemars Piguet'],
            ],
            'aliases' => [
                'Audemars Piguet',
                'Audemars',
                'Audemard',
                'AP',
                'Royal Oak',
                'AP Royal Oak',
                'Royal Oak Skeleton',
                'Royal Oak Openworked',
                'AP Skeleton',
                'AP Openworked',
                'AP iced out',
                'AP moissanite',
            ],
            'keywords' => [
                'rose gold',
                'or rose',
                'skeleton',
                'squelette',
                'openworked',
                'integrated bracelet',
                'iced out',
                'moissanite',
                'VVS',
            ],
        ],

        'square-bicolor-paved' => [
            'families' => [
                ['value' => 'cartier', 'label' => 'Cartier'],
            ],
            'aliases' => [
                'Cartier',
                'Cartier Santos',
                'Santos',
                'Santos Cartier',
                'Cartier two tone',
                'Cartier bicolore',
                'Santos two tone',
                'Cartier iced out',
                'Cartier moissanite',
            ],
            'keywords' => [
                'square',
                'carree',
                'carrée',
                'bicolore',
                'two tone',
                'two-tone',
                'pave',
                'pavé',
                'roman',
                'romains',
                'iced out',
                'moissanite',
                'VVS',
            ],
        ],

        'women-pink' => [
            'families' => [
                ['value' => 'rolex', 'label' => 'Rolex'],
            ],
            'aliases' => [
                'Rolex',
                'Rolex Datejust',
                'Datejust',
                'Lady Datejust',
                'Rolex lady',
                'Rolex women',
                'Rolex femme',
                'Rolex pink',
                'Rolex rose',
                'Rolex iced out',
                'Rolex moissanite',
            ],
            'keywords' => [
                '36 mm',
                'women',
                'femme',
                'pink',
                'rose',
                'jubilee',
                'iced out',
                'moissanite',
                'VVS',
            ],
        ],

        'women-square-36' => [
            'families' => [
                ['value' => 'cartier', 'label' => 'Cartier'],
            ],
            'aliases' => [
                'Cartier',
                'Cartier Santos',
                'Santos',
                'Santos Cartier',
                'Cartier women',
                'Cartier femme',
                'Santos 36',
                'Cartier iced out',
                'Cartier moissanite',
            ],
            'keywords' => [
                '36 mm',
                'women',
                'femme',
                'square',
                'carree',
                'carrée',
                'white dial',
                'cadran blanc',
                'roman',
                'romains',
                'iced out',
                'moissanite',
                'VVS',
            ],
        ],

        'presidentielle-bicolore-romains' => [
            'families' => [
                ['value' => 'cartier', 'label' => 'Cartier'],
            ],
            'aliases' => [
                'Cartier',
                'Cartier Tank',
                'Tank',
                'Tank Cartier',
                'Cartier leather',
                'Cartier cuir',
                'Cartier roman',
                'Cartier iced out',
                'Cartier moissanite',
            ],
            'keywords' => [
                'square',
                'carree',
                'carrée',
                'white dial',
                'cadran blanc',
                'black leather',
                'cuir noir',
                'roman',
                'romains',
                'iced out',
                'moissanite',
                'VVS',
            ],
        ],

        'geometrique-bicolore' => [
            'families' => [
                ['value' => 'patek-philippe', 'label' => 'Patek Philippe'],
            ],
            'aliases' => [
                'Patek Philippe',
                'Patek',
                'Patek Philip',
                'Nautilus',
                'Patek Nautilus',
                'Patek Philippe Nautilus',
                'Nautilus iced out',
                'Patek iced out',
                'Patek bustdown',
                'Patek moissanite',
            ],
            'keywords' => [
                'geometric',
                'geometrique',
                'géométrique',
                'bicolore',
                'two tone',
                'two-tone',
                'integrated bracelet',
                'bracelet integre',
                'iced out',
                'moissanite',
                'VVS',
            ],
        ],

        'presidentielle-bicolore-champagne' => [
            'families' => [
                ['value' => 'rolex', 'label' => 'Rolex'],
            ],
            'aliases' => [
                'Rolex',
                'Rolex Day-Date',
                'Rolex Day Date',
                'Day-Date',
                'Day Date',
                'Daydate',
                'Rolex President',
                'Rolex Presidential',
                'President',
                'Presidential',
                'Rolex champagne',
                'Rolex two tone',
                'Rolex bicolore',
                'Rolex iced out',
                'Rolex moissanite',
            ],
            'keywords' => [
                'champagne',
                'bicolore',
                'two tone',
                'two-tone',
                'gold',
                'or',
                'silver',
                'argent',
                'iced out',
                'moissanite',
                'VVS',
            ],
        ],

        'cadran-bleu-roi' => [
            'families' => [
                ['value' => 'rolex', 'label' => 'Rolex'],
            ],
            'aliases' => [
                'Rolex',
                'Rolex Day-Date',
                'Rolex Day Date',
                'Rolex Datejust',
                'Datejust',
                'Rolex President',
                'President',
                'Rolex blue',
                'Rolex bleu',
                'Rolex iced out',
                'Rolex moissanite',
            ],
            'keywords' => [
                'blue',
                'bleu',
                'royal blue',
                'bleu roi',
                'roman',
                'romains',
                'day',
                'date',
                'silver',
                'argent',
                'iced out',
                'moissanite',
                'VVS',
            ],
        ],

        'chronographe-camouflage' => [
            'families' => [
                ['value' => 'audemars-piguet', 'label' => 'Audemars Piguet'],
            ],
            'aliases' => [
                'Audemars Piguet',
                'Audemars',
                'Audemard',
                'AP',
                'Royal Oak',
                'Royal Oak Offshore',
                'AP Offshore',
                'Audemars Offshore',
                'AP chronograph',
                'AP iced out',
                'AP moissanite',
            ],
            'keywords' => [
                'chronograph',
                'chronographe',
                'camouflage',
                'camo',
                'sport',
                'iced out',
                'moissanite',
                'VVS',
            ],
        ],

        'bleue-argent-romains' => [
            'families' => [
                ['value' => 'rolex', 'label' => 'Rolex'],
            ],
            'aliases' => [
                'Rolex',
                'Rolex Day-Date',
                'Rolex Day Date',
                'Day-Date',
                'Day Date',
                'Daydate',
                'Rolex President',
                'President',
                'Rolex blue',
                'Rolex bleu',
                'Rolex silver',
                'Rolex argent',
                'Rolex iced out',
                'Rolex moissanite',
            ],
            'keywords' => [
                'blue',
                'bleu',
                'silver',
                'argent',
                'roman',
                'romains',
                'day',
                'date',
                'jubilee',
                'iced out',
                'moissanite',
                'VVS',
            ],
        ],

        'geometrique-or-jaune-cadran-vert' => [
            'families' => [
                ['value' => 'patek-philippe', 'label' => 'Patek Philippe'],
            ],
            'aliases' => [
                'Patek Philippe',
                'Patek',
                'Patek Philip',
                'Nautilus',
                'Patek Nautilus',
                'Patek Philippe Nautilus',
                'Patek vert',
                'Patek green',
                'Nautilus vert',
                'Nautilus green',
                'Patek gold',
                'Patek or',
                'Patek or jaune',
                'Patek yellow gold',
                'Patek gold green',
                'Nautilus gold green',
                'Patek iced out',
                'Patek bustdown',
                'Patek moissanite',
                'Patek VVS',
            ],
            'keywords' => [
                '41 mm',
                'green',
                'vert',
                'gold',
                'or',
                'yellow gold',
                'or jaune',
                'geometric',
                'geometrique',
                'géométrique',
                'integrated bracelet',
                'bracelet integre',
                'iced out',
                'bustdown',
                'moissanite',
                'VVS',
            ],
        ],
    ],
];